server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    #mysql驱动包
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://10.168.99.247:3306/vr?useOldAliasMetadataBehavior=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&amp;autoReconnectForPools=true
    #url: jdbc:mysql://10.168.99.247:3306/vr?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
    url: jdbc:mysql://10.168.99.247:3306/vr_test_0619?useUnicode=true&amp;characterEncoding=utf-8
    userName: vr
    password: vr

eureka:
  client:
    #表示注册到注册中心
    register-with-eureka: true
    #从eurekaServer抓取已有的注册信息
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #所有Entity别名类所在包
  type-aliases-package: com.atguigu.springcloud.entities
